//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUERM_RRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnManager
    {
        public string ColumnName { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<bool> Hidden { get; set; }
    }
}
