//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUERM_RRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public System.Guid SCH_ID { get; set; }
        public string SCH_StewardDomain { get; set; }
        public string SCH_RetentionArea { get; set; }
        public string SCH_RetentionSubArea { get; set; }
        public Nullable<int> SCH_AreaScopeId { get; set; }
        public string SCH_RetentionAreaDescription { get; set; }
        public string SCH_Type { get; set; }
        public Nullable<int> SCH_OfficeId { get; set; }
        public string SCH_Coordinator { get; set; }
        public string SCH_RecordSeries { get; set; }
        public string SCH_RecordSeriesCode { get; set; }
        public string SCH_Description { get; set; }
        public Nullable<int> SCH_RetentionId { get; set; }
        public string SCH_Active { get; set; }
        public string SCH_Vital { get; set; }
        public Nullable<int> SCH_GoverningStatutesId { get; set; }
        public Nullable<int> SCH_GoverningRegulationsId { get; set; }
        public Nullable<int> SCH_GoverningPoliciesId { get; set; }
        public string SCH_Reason { get; set; }
        public Nullable<int> SCH_RecordMedium { get; set; }
        public Nullable<int> SCH_RetainerId { get; set; }
        public Nullable<int> SCH_DispositionId { get; set; }
        public Nullable<bool> SCH_RquiresCertDestruction { get; set; }
        public Nullable<System.DateTime> SCH_CreationDate { get; set; }
    
        public virtual ScheduleViewModel AreaScope { get; set; }
        public virtual DispositionOption DispositionOption { get; set; }
        public virtual GoverningPolicy GoverningPolicy { get; set; }
        public virtual GoverningRegulation GoverningRegulation { get; set; }
        public virtual GoverningStatute GoverningStatute { get; set; }
        public virtual OfficeOfRecord OfficeOfRecord { get; set; }
        public virtual OfficialRecordMedium OfficialRecordMedium { get; set; }
        public virtual Retainer Retainer { get; set; }
        public virtual Retention Retention { get; set; }
    }
}
